# Site settings
title: alexa.sc

baseurl: "" # the subpath of your site, e.g. /blog
url: "alexa.sc" # the base hostname & protocol for your site


social:
  - title: linkedin
    url: https://www.linkedin.com/in/alexa-schlegel-92b0ab63
  - title: twitter
    url: https://twitter.com/alexaschlegel
  - title: github
    url: https://github.com/aschle